import { useState } from 'react';
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Layout.module.css'
import Navigation from '../components/Navigation/index.js'
import Home from '../components/Home/index.js'
import User from '../components/User/index.js'
import MessageBoard from '../components/MessageBoard';

export default function Layout() {
  const[panel, setPanel] = useState(0);

  let currentPanel;
  if (panel === 0) {
    currentPanel = <Home />;
  } else if (panel === 1) {
    currentPanel = <MessageBoard />;
  } else if (panel === 2) {
    currentPanel = <User setPanel={setPanel}/>;
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation setPanel={setPanel} />
      <div className={styles.container}>
        {currentPanel}
        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{' '}
            <span className={styles.logo}>
              <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
            </span>
          </a>
        </footer>
      </div>
    </>

  )
}
